#!/bin/sh
set -ex
# export PYTHONPATH=C:/Python38

scenarioi='SSP585 SSP119 SSP126 SSP245 SSP370'
realmi='low_ecs high_ecs mean'
echo 'scenario,realm' > tmpdat0
for scenariot in $scenarioi ; do
  for realmt in $realmi ; do
     echo ${scenariot}','${realmt} > tmpdat
     cat tmpdat0 tmpdat > emulator.csv
     python3 emulator_ch4.py
  done
done
rm -rf tmpdat0 tmpdat
